name: release

on: 
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up build args
      run: |
        echo "MAJOR_VERSION=${GITHUB_REF_NAME%%.*}" >> $GITHUB_ENV
        echo "MINOR_VERSION=${GITHUB_REF_NAME%.*}" >> $GITHUB_ENV
        echo "BUILD_VERSION=${GITHUB_REF_NAME%-*}" >> $GITHUB_ENV
        echo "TAG_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: vergilgao
        password: ${{ secrets.DOCKERHUB_TOKEN }}

 

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          virgil/mdc:${{ env.MAJOR_VERSION }}
          virgil/mdc:${{ env.MINOR_VERSION }}
          virgil/mdc:${{ env.BUILD_VERSION }}
          virgil/mdc:${{ env.TAG_VERSION }}
          virgil/mdc:latest
           
        build-args: |
          VERSION=${{ env.BUILD_VERSION }}
          BUILD_DATE=${{ env.BUILD_DATE }} 
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}    
